-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "17")

-- Settings
hl.config({
    decoration = {
        blur = {
            xray = false,
        },
    },
    general = {
        allow_tearing = false,
        layout = "dwindle",
    },
    input = {
        sensitivity = -0.2,
    },
    misc = {
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = true,
        vrr = 0,
    },
})

-- Bezier curves
hl.curve("menu_decel", { type = "bezier", points = { {0.1, 1.0}, {0.0, 1.0} } })

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.5,
    bezier = "menu_decel",
    style = "slidefade 18%",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = true,
})

-- Keybinds
hl.unbind("SUPER + Left")
hl.bind("SUPER + Left", hl.dsp.focus({ direction = "left" }))
hl.unbind("SUPER + Right")
hl.bind("SUPER + Right", hl.dsp.focus({ direction = "right" }))
