-- Generated by nwg-displays on 2026-08-30 at 17:23:48. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@200.0",
    position = "0x0",
    scale = 1
})
